<a href="https://colab.research.google.com/github/Nitai1995/Tensorflow/blob/main/TensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("nitai")

nitai


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [ ]:
x = tf.constant(4, dtype=tf.float32, shape=(1,1))
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [ ]:
y = tf.ones(shape=(2,2))
y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
z= tf.zeros((2,3))
z

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
i = tf.eye(3)
i

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
# Normal Distribution:
n = tf.random.normal((1,3), mean = 0, stddev=1)
print(n)

tf.Tensor([[-2.1892343  -0.22457689 -0.2647174 ]], shape=(1, 3), dtype=float32)


In [ ]:
#Uniform Distribution:
u = tf.random.uniform((3,1), minval=0, maxval=10)
print(u)

tf.Tensor(
[[2.4157321 ]
 [0.32256126]
 [9.008523  ]], shape=(3, 1), dtype=float32)


In [ ]:
#Range:
r1 = tf.range(5)
print(r1)
r2 = tf.range(start=1, limit=10, delta=2)
print(r2)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
#Casting to different types:
g = 12
print(g)
g=tf.cast(g, tf.float32)
print(g)

12
tf.Tensor(12.0, shape=(), dtype=float32)


In [ ]:
#Summing Logic
x = tf.constant([1,2,3])
y= tf.constant([9,8,7])
z = tf.add(x,y)
print(z)
# or
z = x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
#Subtract Logic
x = tf.constant([1,2,3])
y= tf.constant([9,8,7])
z = tf.subtract(x,y)
print(z)
# or
z = x-y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [ ]:
#Multiply Logic
x = tf.constant([1,2,3])
y= tf.constant([9,8,7])
z = tf.multiply(x,y)
print(z)
# or
z = x*y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [ ]:
#Division Logic
x = tf.constant([1,2,3])
y= tf.constant([9,8,7])
z = tf.divide(x,y)
print(z)
# or
z = x/y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [ ]:
#Exponentiation Logic
x = tf.constant([1,2,3])
z = x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [ ]:
#DotProduct Logic
x = tf.constant([1,2,3])
y= tf.constant([9,8,7])
z = tf.tensordot(x,y, axes=1)
print(z)
# or
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
#Matrix Multiplication:
#Summing Logic
print(n)
print(u)
z = tf.matmul(n,u)
print(z)
# or
z = n@u
print(z)

tf.Tensor([[-2.1892343  -0.22457689 -0.2647174 ]], shape=(1, 3), dtype=float32)
tf.Tensor(
[[2.4157321 ]
 [0.32256126]
 [9.008523  ]], shape=(3, 1), dtype=float32)
tf.Tensor([[-7.745756]], shape=(1, 1), dtype=float32)
tf.Tensor([[-7.745756]], shape=(1, 1), dtype=float32)


In [ ]:
#Indexing
e = tf.range(9)
print(e)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
e[:]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
e[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
e[3:-1]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
e[:-1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [ ]:
e[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
e[::2]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>

In [ ]:
e[::-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [ ]:
indices = tf.constant([1,3,4,7])
e_ind = tf.gather(e,indices)
print(e_ind)

tf.Tensor([1 3 4 7], shape=(4,), dtype=int32)


In [ ]:
f= tf.constant([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
f[0,]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
f[:,2]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [ ]:
f[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
f[-1,-1]

<tf.Tensor: shape=(), dtype=int32, numpy=9>

Reshaping:

In [ ]:
j = tf.reshape(e,(3,3))
print(j)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [ ]:
h = tf.transpose(j)
print(h)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
